name: Monitor Refugio

on:
  schedule:
    - cron: '0 8,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Copiar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar librerías
      run: pip install requests

    # 1. DESCARGAMOS EL HASH DEL DÍA ANTERIOR DESDE LA NUBE DE GITHUB
    - name: Descargar hash anterior
      uses: actions/download-artifact@v4
      with:
        name: hash-control-data
        path: .
      continue-on-error: true # Si es la primera vez y no existe, no pasa nada, el script continúa

    # 2. EJECUTAMOS EL SCRIPT (abrirá el archivo si se descargó en el paso anterior)
    - name: Ejecutar script de control
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python check_refugio.py

    # 3. SUBIMOS EL NUEVO ARCHIVO TEXTO A LA NUBE (Reemplaza al anterior sin hacer commits)
    - name: Subir nuevo hash a la nube de GitHub
      uses: actions/upload-artifact@v4
      with:
        name: hash-control-data
        path: ultimo_hash_refugio.txt
        overwrite: true # Sobrescribe el archivo anterior para que no ocupe espacio extra
