name: Monitor Refugio

on:
  schedule:
    - cron: '12 6,18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Copiar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar librerías
      run: pip install requests

    # Usamos la caché de GitHub que es silenciosa y no genera errores visuales
    - name: Recuperar caché del Hash
      uses: actions/cache@v3
      with:
        path: ultimo_hash_refugio.txt
        key: hash-refugio-cache

    - name: Ejecutar script de control
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python check_refugio.py
